---
# This is the main tasks file for nginx role
- include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family != 'Debian'

- include: install_Redhat.yml
  when: ansible_os_family == 'RedHat'

- include: install_Debian.yml
  when: ansible_os_family == 'Debian'

#- include: install.yml
- include: configure.yml
- include: service.yml
